export interface AfricanCountryConfig {
  code: string;
  name: string;
  flag: string;
  defaultLanguage: 'pt' | 'en' | 'fr' | 'ar' | 'sw' | 'af';
  currencyCode: string;
  currencySymbol: string;
  dateFormat: string;
  numberFormat: '1,250.00' | '1.250,00' | '1 250,00';
  taxLabel: string;
  taxRate: number;
  phoneCountryCode: string;
  mobileMoneyOptions: string[];
}

export const AFRICAN_COUNTRIES: AfricanCountryConfig[] = [
  {
    code: 'DZ',
    name: 'Argélia (Algeria)',
    flag: '🇩🇿',
    defaultLanguage: 'ar',
    currencyCode: 'DZD',
    currencySymbol: 'DA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'TVA',
    taxRate: 19,
    phoneCountryCode: '+213',
    mobileMoneyOptions: ['Mobilis', 'Djezzy Cash', 'BaridiMob'],
  },
  {
    code: 'AO',
    name: 'Angola',
    flag: '🇦🇴',
    defaultLanguage: 'pt',
    currencyCode: 'AOA',
    currencySymbol: 'Kz',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'IVA',
    taxRate: 14,
    phoneCountryCode: '+244',
    mobileMoneyOptions: ['Unitel Lwini', 'e-Kwanza', 'Banco Sol'],
  },
  {
    code: 'BJ',
    name: 'Benim (Benin)',
    flag: '🇧🇯',
    defaultLanguage: 'fr',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+229',
    mobileMoneyOptions: ['MTN MoMo', 'Moov Flooz'],
  },
  {
    code: 'BW',
    name: 'Botsuana (Botswana)',
    flag: '🇧🇼',
    defaultLanguage: 'en',
    currencyCode: 'BWP',
    currencySymbol: 'P',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 14,
    phoneCountryCode: '+267',
    mobileMoneyOptions: ['MyZaka (Mascom)', 'Orange Money', 'Smarteel'],
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    flag: '🇧🇫',
    defaultLanguage: 'fr',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+226',
    mobileMoneyOptions: ['Orange Money', 'MobiCash (Telmob)'],
  },
  {
    code: 'BI',
    name: 'Burundi',
    flag: '🇧🇮',
    defaultLanguage: 'fr',
    currencyCode: 'BIF',
    currencySymbol: 'FrBu',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+257',
    mobileMoneyOptions: ['LumiCash', 'Ecocash (Econet)'],
  },
  {
    code: 'CV',
    name: 'Cabo Verde (Cape Verde)',
    flag: '🇨🇻',
    defaultLanguage: 'pt',
    currencyCode: 'CVE',
    currencySymbol: 'Esc',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'IVA',
    taxRate: 15,
    phoneCountryCode: '+238',
    mobileMoneyOptions: ['vinti4', 'Pagali'],
  },
  {
    code: 'CM',
    name: 'Camarões (Cameroon)',
    flag: '🇨🇲',
    defaultLanguage: 'fr',
    currencyCode: 'XAF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 19.25,
    phoneCountryCode: '+237',
    mobileMoneyOptions: ['MTN MoMo', 'Orange Money'],
  },
  {
    code: 'CF',
    name: 'República Centro-Africana (CAR)',
    flag: '🇨🇫',
    defaultLanguage: 'fr',
    currencyCode: 'XAF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 19,
    phoneCountryCode: '+236',
    mobileMoneyOptions: ['Orange Money', 'Telecel Cash'],
  },
  {
    code: 'TD',
    name: 'Chade (Chad)',
    flag: '🇹🇩',
    defaultLanguage: 'fr',
    currencyCode: 'XAF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+235',
    mobileMoneyOptions: ['Tigo Cash', 'Airtel Money'],
  },
  {
    code: 'KM',
    name: 'Comores (Comoros)',
    flag: '🇰🇲',
    defaultLanguage: 'fr',
    currencyCode: 'KMF',
    currencySymbol: 'CF',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'TVA',
    taxRate: 10,
    phoneCountryCode: '+269',
    mobileMoneyOptions: ['Huri Money', 'Mvola'],
  },
  {
    code: 'CG',
    name: 'Congo-Brazzaville',
    flag: '🇨🇬',
    defaultLanguage: 'fr',
    currencyCode: 'XAF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+242',
    mobileMoneyOptions: ['MTN MoMo', 'Airtel Money'],
  },
  {
    code: 'CD',
    name: 'R.D. Congo (DRC)',
    flag: '🇨🇩',
    defaultLanguage: 'fr',
    currencyCode: 'CDF',
    currencySymbol: 'FC',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'TVA',
    taxRate: 16,
    phoneCountryCode: '+243',
    mobileMoneyOptions: ['M-Pesa (Vodacom)', 'Airtel Money', 'Orange Money', 'Afrimoney'],
  },
  {
    code: 'DJ',
    name: 'Djibuti (Djibouti)',
    flag: '🇩🇯',
    defaultLanguage: 'fr',
    currencyCode: 'DJF',
    currencySymbol: 'Fdj',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'TVA',
    taxRate: 7,
    phoneCountryCode: '+253',
    mobileMoneyOptions: ['D-Money', 'Evatis'],
  },
  {
    code: 'EG',
    name: 'Egito (Egypt)',
    flag: '🇪🇬',
    defaultLanguage: 'ar',
    currencyCode: 'EGP',
    currencySymbol: '£E',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 14,
    phoneCountryCode: '+20',
    mobileMoneyOptions: ['Vodafone Cash', 'InstaPay', 'Orange Cash', 'Etisalat Cash'],
  },
  {
    code: 'GQ',
    name: 'Guiné Equatorial',
    flag: '🇬🇶',
    defaultLanguage: 'fr',
    currencyCode: 'XAF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 15,
    phoneCountryCode: '+240',
    mobileMoneyOptions: ['Muni Money', 'EG-Pay'],
  },
  {
    code: 'ER',
    name: 'Eritreia (Eritrea)',
    flag: '🇪🇷',
    defaultLanguage: 'ar',
    currencyCode: 'ERN',
    currencySymbol: 'Nfk',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 4,
    phoneCountryCode: '+291',
    mobileMoneyOptions: ['Eri-Cash'],
  },
  {
    code: 'SZ',
    name: 'Eswatini',
    flag: '🇸🇿',
    defaultLanguage: 'en',
    currencyCode: 'SZL',
    currencySymbol: 'L',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+268',
    mobileMoneyOptions: ['MTN MoMo', 'e-Mlangeni'],
  },
  {
    code: 'ET',
    name: 'Etiópia (Ethiopia)',
    flag: '🇪🇹',
    defaultLanguage: 'en',
    currencyCode: 'ETB',
    currencySymbol: 'Br',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+251',
    mobileMoneyOptions: ['Telebirr', 'CBE Birr', 'HelloCash'],
  },
  {
    code: 'GA',
    name: 'Gabão (Gabon)',
    flag: '🇬🇦',
    defaultLanguage: 'fr',
    currencyCode: 'XAF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+241',
    mobileMoneyOptions: ['Airtel Money', 'Moov MoNo', 'BGFIMobile'],
  },
  {
    code: 'GM',
    name: 'Gâmbia (Gambia)',
    flag: '🇬🇲',
    defaultLanguage: 'en',
    currencyCode: 'GMD',
    currencySymbol: 'D',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+220',
    mobileMoneyOptions: ['QMoney (QCell)', 'Airtel Money', 'Wave'],
  },
  {
    code: 'GH',
    name: 'Gana (Ghana)',
    flag: '🇬🇭',
    defaultLanguage: 'en',
    currencyCode: 'GHS',
    currencySymbol: 'GH₵',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15, // Plus individual components if overridden
    phoneCountryCode: '+233',
    mobileMoneyOptions: ['MTN MoMo', 'Vodafone Cash', 'AirtelTigo Money'],
  },
  {
    code: 'GN',
    name: 'Guiné (Guinea)',
    flag: '🇬🇳',
    defaultLanguage: 'fr',
    currencyCode: 'GNF',
    currencySymbol: 'FG',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+224',
    mobileMoneyOptions: ['Orange Money', 'MTN MoMo', 'SilyPay'],
  },
  {
    code: 'GW',
    name: 'Guiné-Bissau',
    flag: '🇬🇼',
    defaultLanguage: 'pt',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 19,
    phoneCountryCode: '+245',
    mobileMoneyOptions: ['MTN MoMo (Spacetel)', 'Orange Money'],
  },
  {
    code: 'CI',
    name: 'Costa do Marfim (Côte d’Ivoire)',
    flag: '🇨🇮',
    defaultLanguage: 'fr',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+225',
    mobileMoneyOptions: ['Orange Money', 'Wave', 'MTN MoMo', 'Moov Flooz'],
  },
  {
    code: 'KE',
    name: 'Quénia (Kenya)',
    flag: '🇰🇪',
    defaultLanguage: 'sw',
    currencyCode: 'KES',
    currencySymbol: 'KSh',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 16,
    phoneCountryCode: '+254',
    mobileMoneyOptions: ['M-Pesa (Safaricom)', 'Airtel Money', 'T-Kash (Telkom)'],
  },
  {
    code: 'LS',
    name: 'Lesoto (Lesotho)',
    flag: '🇱🇸',
    defaultLanguage: 'en',
    currencyCode: 'LSL',
    currencySymbol: 'L',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+266',
    mobileMoneyOptions: ['M-Pesa', 'EcoCash'],
  },
  {
    code: 'LR',
    name: 'Libéria (Liberia)',
    flag: '🇱🇷',
    defaultLanguage: 'en',
    currencyCode: 'LRD',
    currencySymbol: '$',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'GST',
    taxRate: 10,
    phoneCountryCode: '+231',
    mobileMoneyOptions: ['Lonestar MTN MoMo', 'Orange Money'],
  },
  {
    code: 'LY',
    name: 'Líbia (Libya)',
    flag: '🇱🇾',
    defaultLanguage: 'ar',
    currencyCode: 'LYD',
    currencySymbol: 'LD',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 0,
    phoneCountryCode: '+218',
    mobileMoneyOptions: ['Sadad', 'Tadawul Pay', 'Mobicash'],
  },
  {
    code: 'MG',
    name: 'Madagáscar (Madagascar)',
    flag: '🇲🇬',
    defaultLanguage: 'fr',
    currencyCode: 'MGA',
    currencySymbol: 'Ar',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 20,
    phoneCountryCode: '+261',
    mobileMoneyOptions: ['Mvola', 'Orange Money (Orange S.A.)', 'Airtel Money'],
  },
  {
    code: 'MW',
    name: 'Maláui (Malawi)',
    flag: '🇲🇼',
    defaultLanguage: 'en',
    currencyCode: 'MWK',
    currencySymbol: 'MK',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 16.5,
    phoneCountryCode: '+265',
    mobileMoneyOptions: ['Airtel Money', 'TNM Mpamba'],
  },
  {
    code: 'ML',
    name: 'Mali',
    flag: '🇲🇱',
    defaultLanguage: 'fr',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+223',
    mobileMoneyOptions: ['Orange Money', 'Wave Mali', 'MTN SikaCard'],
  },
  {
    code: 'MR',
    name: 'Mauritânia (Mauritania)',
    flag: '🇲🇷',
    defaultLanguage: 'ar',
    currencyCode: 'MRU',
    currencySymbol: 'UM',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'TVA',
    taxRate: 16,
    phoneCountryCode: '+222',
    mobileMoneyOptions: ['Masrifi', 'Bankily', 'Sadad'],
  },
  {
    code: 'MU',
    name: 'Maurícia (Mauritius)',
    flag: '🇲🇺',
    defaultLanguage: 'en',
    currencyCode: 'MUR',
    currencySymbol: '₨',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+230',
    mobileMoneyOptions: ['JuiceByMCB', 'my.t money', 'Blink'],
  },
  {
    code: 'MA',
    name: 'Marrocos (Morocco)',
    flag: '🇲🇦',
    defaultLanguage: 'ar',
    currencyCode: 'MAD',
    currencySymbol: 'DH',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'TVA',
    taxRate: 20,
    phoneCountryCode: '+212',
    mobileMoneyOptions: ['Inwi Money', 'Maroc Telecom Cash', 'Orange Money'],
  },
  {
    code: 'MZ',
    name: 'Moçambique (Mozambique)',
    flag: '🇲🇿',
    defaultLanguage: 'pt',
    currencyCode: 'MZN',
    currencySymbol: 'MT',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'IVA',
    taxRate: 17,
    phoneCountryCode: '+258',
    mobileMoneyOptions: ['M-Pesa (Vodacom)', 'e-Mola (Tmcel)', 'Mkesh (BCI)'],
  },
  {
    code: 'NA',
    name: 'Namíbia (Namibia)',
    flag: '🇳🇦',
    defaultLanguage: 'af',
    currencyCode: 'NAD',
    currencySymbol: 'N$',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+264',
    mobileMoneyOptions: ['e-Wallet (FNB)', 'PayToday', 'EasyWallet'],
  },
  {
    code: 'NE',
    name: 'Níger (Niger)',
    flag: '🇳🇪',
    defaultLanguage: 'fr',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 19,
    phoneCountryCode: '+227',
    mobileMoneyOptions: ['Airtel Money', 'Moov Flooz'],
  },
  {
    code: 'NG',
    name: 'Nigéria (Nigeria)',
    flag: '🇳🇬',
    defaultLanguage: 'en',
    currencyCode: 'NGN',
    currencySymbol: '₦',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 7.5,
    phoneCountryCode: '+234',
    mobileMoneyOptions: ['OPay', 'PalmPay', 'Kuda', 'MTN MoMo', 'Paga'],
  },
  {
    code: 'RW',
    name: 'Ruanda (Rwanda)',
    flag: '🇷🇼',
    defaultLanguage: 'en',
    currencyCode: 'RWF',
    currencySymbol: 'RwF',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 18,
    phoneCountryCode: '+250',
    mobileMoneyOptions: ['MTN MoMo', 'Airtel Money'],
  },
  {
    code: 'ST',
    name: 'São Tomé e Príncipe',
    flag: '🇸🇹',
    defaultLanguage: 'pt',
    currencyCode: 'STN',
    currencySymbol: 'Db',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'IVA',
    taxRate: 7.5,
    phoneCountryCode: '+239',
    mobileMoneyOptions: ['Dobra Pay', 'E-Dobra'],
  },
  {
    code: 'SN',
    name: 'Senegal',
    flag: '🇸🇳',
    defaultLanguage: 'fr',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+221',
    mobileMoneyOptions: ['Orange Money', 'Wave Senegal', 'Free Money'],
  },
  {
    code: 'SC',
    name: 'Seicheles (Seychelles)',
    flag: '🇸🇨',
    defaultLanguage: 'en',
    currencyCode: 'SCR',
    currencySymbol: 'SR',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+248',
    mobileMoneyOptions: ['Airtel Money', 'Seychelles Pay'],
  },
  {
    code: 'SL',
    name: 'Serra Leoa (Sierra Leone)',
    flag: '🇸🇱',
    defaultLanguage: 'en',
    currencyCode: 'SLE',
    currencySymbol: 'Le',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'GST',
    taxRate: 15,
    phoneCountryCode: '+232',
    mobileMoneyOptions: ['Orange Money', 'Afrimoney'],
  },
  {
    code: 'SO',
    name: 'Somália (Somalia)',
    flag: '🇸🇴',
    defaultLanguage: 'ar',
    currencyCode: 'SOS',
    currencySymbol: 'Sh',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 5,
    phoneCountryCode: '+252',
    mobileMoneyOptions: ['EVC Plus (Hormuud)', 'Zaad (Telesom)', 'Sahal'],
  },
  {
    code: 'ZA',
    name: 'África do Sul (South Africa)',
    flag: '🇿🇦',
    defaultLanguage: 'en',
    currencyCode: 'ZAR',
    currencySymbol: 'R',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+27',
    mobileMoneyOptions: ['SnapScan', 'Zapper', 'FNB Pay', 'Nedbank Money'],
  },
  {
    code: 'SS',
    name: 'Sudão do Sul (South Sudan)',
    flag: '🇸🇸',
    defaultLanguage: 'en',
    currencyCode: 'SSP',
    currencySymbol: '£',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 18,
    phoneCountryCode: '+211',
    mobileMoneyOptions: ['m-Gurush'],
  },
  {
    code: 'SD',
    name: 'Sudão (Sudan)',
    flag: '🇸🇩',
    defaultLanguage: 'ar',
    currencyCode: 'SDG',
    currencySymbol: '£SD',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 17,
    phoneCountryCode: '+249',
    mobileMoneyOptions: ['BOK Pay', 'SyberPay', 'Amaon Pay'],
  },
  {
    code: 'TZ',
    name: 'Tanzânia (Tanzania)',
    flag: '🇹🇿',
    defaultLanguage: 'sw',
    currencyCode: 'TZS',
    currencySymbol: 'TSh',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 18,
    phoneCountryCode: '+255',
    mobileMoneyOptions: ['M-Pesa (Safaricom)', 'Tigo Pesa', 'Airtel Money', 'Halopesa'],
  },
  {
    code: 'TG',
    name: 'Togo',
    flag: '🇹🇬',
    defaultLanguage: 'fr',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1 250,00',
    taxLabel: 'TVA',
    taxRate: 18,
    phoneCountryCode: '+228',
    mobileMoneyOptions: ['T-Money', 'Moov Flooz (Moov)'],
  },
  {
    code: 'TN',
    name: 'Tunísia (Tunisia)',
    flag: '🇹🇳',
    defaultLanguage: 'ar',
    currencyCode: 'TND',
    currencySymbol: 'DT',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1.250,00',
    taxLabel: 'TVA',
    taxRate: 19,
    phoneCountryCode: '+216',
    mobileMoneyOptions: ['Mobicash', 'MDinar'],
  },
  {
    code: 'UG',
    name: 'Uganda',
    flag: '🇺🇬',
    defaultLanguage: 'en',
    currencyCode: 'UGX',
    currencySymbol: 'UgShs',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 18,
    phoneCountryCode: '+256',
    mobileMoneyOptions: ['MTN MoMo', 'Airtel Money'],
  },
  {
    code: 'ZM',
    name: 'Zâmbia (Zambia)',
    flag: '🇿🇲',
    defaultLanguage: 'en',
    currencyCode: 'ZMW',
    currencySymbol: 'ZK',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 16,
    phoneCountryCode: '+260',
    mobileMoneyOptions: ['MTN MoMo', 'Airtel Money', 'Zamtel Kwacha'],
  },
  {
    code: 'ZW',
    name: 'Zimbábue (Zimbabwe)',
    flag: '🇿🇼',
    defaultLanguage: 'en',
    currencyCode: 'ZWG',
    currencySymbol: 'ZiG',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: '1,250.00',
    taxLabel: 'VAT',
    taxRate: 15,
    phoneCountryCode: '+263',
    mobileMoneyOptions: ['EcoCash', 'OneMoney', 'InnBucks'],
  },
];
